<?php

global $switch_styles_styles;
$switch_styles_styles = array('default', 'hi-contrast');

/**
 * @file
 * Framework for themes to easily add stylesheet switching functionality.
 */

/**
 * Implements hook_block_info().
 */
function switch_styles_block_info() {
  $blocks['switch_styles'] = array(
    'info' => t('Style Switcher'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function switch_styles_block_view($delta) {
  switch ($delta) {
    case 'switch_styles':

      drupal_add_library('system', 'jquery.cookie', TRUE);

      global $switch_styles_styles;

      $links = array();
      foreach ($switch_styles_styles as $style) {
        $links[] = l($style, current_path(), 
                     array(
                           'query' => array('switch_styles' => $style),
                           'attributes' => array('data-target-style' => $style),                           
                           ));
      }

      $block['subject'] = t('Style Switcher');
      $block['content'] = theme('item_list', array('items' => $links));
      return $block;
  }
}

/**
 * Implements hook_menu().
 */
function switch_styles_menu() {
  $items['admin/config/system/switch_styles'] = array(
    'title' => 'Switch_Styles',
    'description' => 'Configure Switch_Styles module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('switch_styles_admin'),
    'access arguments' => array('administer site'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Add a settings form
 */
function switch_styles_admin() {
  $form = array();

  $form['switch_styles_enable_overlay'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Overlay'),
    '#default_value' => variable_get('switch_styles_enable_overlay', 1),
    '#description' => t("Enable the overlay and fade when switching stylesheets"),
    '#required' => FALSE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_preprocess().
 */
function switch_styles_preprocess (&$variables, $hook) {

  if ($hook == 'html') {
    global $switch_styles_styles;

    /* we change the cookie based on a query parameter */
    $query_params = drupal_get_query_parameters();
    if (array_key_exists('switch_styles', $query_params)) {
      set_current_style($query_params['switch_styles']);
      $current_style = $query_params['switch_styles'];
    } else {
      $current_style = get_current_style();
    }
    $variables['classes_array'][] = $current_style;
  }
}

function get_current_style () {

  if (array_key_exists('Drupal_visitor_switch_styles', $_COOKIE))
    return $_COOKIE['Drupal_visitor_switch_styles'];
  else
    return 'default';
}

function set_current_style ($style) {

  user_cookie_save(array('switch_styles' => $style));
}